# Generated by Django 5.2.6 on 2025-10-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(blank=True, help_text='A brief summary of the movie.'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_video_id',
            field=models.CharField(blank=True, help_text="The YouTube video ID (e.g., 'dQw4w9WgXcQ')", max_length=50),
        ),
    ]
