# Generated by Django 5.2.6 on 2025-10-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_synopsis_movie_trailer_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='detail_poster_url',
            field=models.URLField(blank=True, help_text='Optional: A wider (landscape) poster for the movie detail page.', max_length=500, null=True),
        ),
    ]
