# Generated by Django 5.2.6 on 2025-11-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_detail_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total revenue generated', max_digits=6),
        ),
    ]
