# Generated by Django 5.2.6 on 2025-11-01 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_revenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, default=0, help_text='Order in which this show appears on the dashboard (lower number first).', null=True)),
                ('movie', models.OneToOneField(help_text='Select a movie to feature on the dashboard.', on_delete=django.db.models.deletion.CASCADE, related_name='featured_entry', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Featured Show (Dashboard)',
                'verbose_name_plural': 'Featured Shows (Dashboard)',
                'ordering': ['position', 'movie__title'],
            },
        ),
    ]
