# Generated by Django 5.2.6 on 2025-11-01 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_featuredshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='featuredshow',
            options={'ordering': ['position'], 'verbose_name': 'Featured Show (Dashboard)', 'verbose_name_plural': 'Featured Shows (Dashboard)'},
        ),
        migrations.AlterField(
            model_name='featuredshow',
            name='movie',
            field=models.OneToOneField(help_text='Select a movie to feature on the dashboard.', on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='featuredshow',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Order on the dashboard (0 comes first, 1 next, etc.)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="DEPRECATED: Use the 'Featured Shows' admin section instead."),
        ),
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total revenue generated', max_digits=12),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.genre'),
        ),
    ]
