# Generated by Django 5.2.6 on 2025-11-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_genre_alter_featuredshow_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.DecimalField(decimal_places=0, default=0.0, help_text='Total revenue generated', max_digits=6),
        ),
        migrations.DeleteModel(
            name='FeaturedShow',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
