# Generated by Django 5.2.6 on 2025-11-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_genre_alter_movie_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
