# Generated by Django 5.2.6 on 2025-11-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_revenue copy'),
        ('movies', '0011_alter_movie_rating'),
    ]

    operations = [
    ]
