# Generated by Django 5.2.6 on 2025-11-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_merge_0004_movie_revenue copy_0011_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.DecimalField(decimal_places=0, default=0.0, help_text='Total revenue generated', max_digits=6),
        ),
    ]
