# Generated by Django 5.2.6 on 2025-11-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_movie_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='votes',
            field=models.PositiveIntegerField(default=0, help_text='Total number of votes for this movie'),
        ),
    ]
