# Generated by Django 5.2.6 on 2025-11-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_show'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={},
        ),
    ]
