# Generated by Django 5.2.6 on 2025-11-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_alter_show_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Show',
        ),
    ]
