# Generated by Django 5.2.6 on 2025-11-07 16:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='repeat_count',
            field=models.PositiveIntegerField(default=1, help_text='How many times to display this movie in the admin dashboard.'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='If checked, this movie will appear in featured sections.'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total revenue generated by this movie.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_video_id',
            field=models.CharField(blank=True, help_text="YouTube video ID (e.g., 'dQw4w9WgXcQ').", max_length=50),
        ),
    ]
