# Generated by Django 5.2.6 on 2025-11-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_movie_repeat_count_alter_movie_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='repeat_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of times this movie should show on the admin dashboard'),
        ),
    ]
