# Generated by Django 5.2.6 on 2025-11-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_alter_movie_repeat_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='repeat_count',
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.DecimalField(decimal_places=0, default=0.0, help_text='Total revenue generated', max_digits=6),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_video_id',
            field=models.CharField(blank=True, help_text="The YouTube video ID (e.g., 'dQw4w9WgXcQ')", max_length=50),
        ),
        migrations.DeleteModel(
            name='Show',
        ),
    ]
