# Generated by Django 5.2.6 on 2025-11-07 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_remove_movie_repeat_count_alter_movie_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hall', models.CharField(blank=True, max_length=100)),
                ('seats_total', models.PositiveIntegerField(default=100)),
                ('seats_booked', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.movie')),
            ],
            options={
                'ordering': ['show_date', 'show_time'],
            },
        ),
    ]
