# Generated by Django 5.2.6 on 2025-11-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
