# Generated by Django 5.2.6 on 2025-11-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='created_at',
            new_name='booked_at',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('reserved', 'reserved'), ('confirmed', 'confirmed')], default='reserved', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.CharField(max_length=8),
        ),
    ]
