# Generated by Django 5.2.6 on 2025-11-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_rename_created_at_booking_booked_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
