# Generated by Django 5.2.6 on 2025-11-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0030_alter_movie_detail_poster_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(help_text='URL of the movie poster', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='show',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
