# Generated by Django 5.2.6 on 2025-11-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0031_alter_movie_poster_url_alter_movie_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default price if show price missing', max_digits=7),
        ),
    ]
