# Generated by Django 5.2.6 on 2025-11-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0032_movie_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='booked_seats',
            field=models.TextField(blank=True, default=''),
        ),
    ]
